services:
  big-box-companion:
    image: larsmikki/big-box-companion:latest
    container_name: big-box-companion
    ports:
      - "3070:3070"
    volumes:
      - big-box-companion-data:/app/data
    restart: always
    environment:
      - DATA_DIR=/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3070/api/health"]
      interval: 300s
      timeout: 5s
      retries: 3

volumes:
  big-box-companion-data:
