services:
  collecter:
    image: larsmikki/collecter:latest
    container_name: collecter
    ports:
      - "3070:3070"
    volumes:
      - collecter-data:/app/data
    restart: always
    environment:
      - DATA_DIR=/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3070/api/health"]
      interval: 300s
      timeout: 5s
      retries: 3

volumes:
  collecter-data:
